"""add breed images

Revision ID: 3cad3cd3e1f5
Revises: d809b29244cb
Create Date: 2026-09-19 01:56:09.454539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cad3cd3e1f5'
down_revision: Union[str, Sequence[str], None] = 'd809b29244cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('alt_text', sa.String(length=250), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_image_breed_id'), 'breed_image', ['breed_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breed_image_breed_id'), table_name='breed_image')
    op.drop_table('breed_image')
    # ### end Alembic commands ###
