"""create breed catalog tables

Revision ID: d809b29244cb
Revises: 4749ac9c2abb
Create Date: 2026-09-19 00:49:56.924169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd809b29244cb'
down_revision: Union[str, Sequence[str], None] = '4749ac9c2abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coat_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('breed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('male_height_min_cm', sa.Float(), nullable=True),
    sa.Column('male_height_max_cm', sa.Float(), nullable=True),
    sa.Column('female_height_min_cm', sa.Float(), nullable=True),
    sa.Column('female_height_max_cm', sa.Float(), nullable=True),
    sa.Column('male_weight_min_kg', sa.Float(), nullable=True),
    sa.Column('male_weight_max_kg', sa.Float(), nullable=True),
    sa.Column('female_weight_min_kg', sa.Float(), nullable=True),
    sa.Column('female_weight_max_kg', sa.Float(), nullable=True),
    sa.Column('lifespan_min_years', sa.SmallInteger(), nullable=True),
    sa.Column('lifespan_max_years', sa.SmallInteger(), nullable=True),
    sa.Column('size_category', sa.String(length=20), nullable=True),
    sa.Column('original_purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("size_category IS NULL OR size_category IN ('small', 'medium', 'large', 'giant')", name='ck_breed_size_category'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['breed_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('breed_coat_type',
    sa.Column('breed_id', sa.UUID(), nullable=False),
    sa.Column('coat_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coat_type_id'], ['coat_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('breed_id', 'coat_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breed_coat_type')
    op.drop_table('breed')
    op.drop_table('coat_type')
    op.drop_table('breed_group')
    # ### end Alembic commands ###
